DROP TABLE IF EXISTS `conductor`;

CREATE TABLE `conductor` (
`ID` INT(10)  NOT NULL AUTO_INCREMENT,
`NOMBRE` VARCHAR(100) NOT NULL ,
`APELLIDO` VARCHAR(100) NOT NULL ,
`DNI` INT(20) NOT NULL ,
`FECHA_NACIMIENTO` DATETIME NOT NULL ,
`GENERO` VARCHAR(50) NOT NULL ,
`EMAIL` VARCHAR(100) NOT NULL ,
`SYS_CREATED_AT` DATETIME NOT NULL ,
`SYS_UPDATED_AT` DATETIME NOT NULL ,
PRIMARY KEY (`ID`)) 
ENGINE = InnoDB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `auto`;

CREATE TABLE `auto` (
`ID` INT(10) NOT NULL AUTO_INCREMENT,
`ID_CONDUCTOR` INT(10) NOT NULL ,
`PATENTE` VARCHAR(10) NOT NULL ,
`MARCA` VARCHAR(50) NOT NULL ,
`MODELO` VARCHAR(50) NOT NULL ,
`ANIO` INT(10) NOT NULL ,
`SYS_CREATED_AT` DATETIME NOT NULL ,
`SYS_UPDATED_AT` DATETIME NOT NULL ,
PRIMARY KEY (`ID`)) 
ENGINE = InnoDB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `tarjeta`;

CREATE TABLE `tarjeta` (
`ID` INT(10) NOT NULL AUTO_INCREMENT,
`NRO_TARJETA` VARCHAR(20) NOT NULL ,
`ID_CONDUCTOR` INT(10) NOT NULL ,
`BANCO_EMISOR` VARCHAR(100) NOT NULL ,
`TIPO_TARJETA` VARCHAR(50) NOT NULL ,
`FECHA_VENCIMIENTO` VARCHAR(4) NOT NULL ,
`SYS_CREATED_AT` DATETIME NOT NULL ,
`SYS_UPDATED_AT` DATETIME NOT NULL ,
PRIMARY KEY (`ID`)) 
ENGINE = InnoDB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `asociado`;

CREATE TABLE `asociado` (
`ID` INT(10) NOT NULL AUTO_INCREMENT,
`RAZON_SOCIAL` VARCHAR(100) NOT NULL ,
`CUIT` VARCHAR(25) NOT NULL ,
`CALLE` VARCHAR(100) NOT NULL ,
`ALTURA` INT(10) NOT NULL ,
`EMAIL` VARCHAR(100) NOT NULL ,
`LATITUD` FLOAT NULL ,
`LONGITUD` FLOAT NULL ,
`SYS_CREATED_AT` DATETIME NOT NULL ,
`SYS_UPDATED_AT` DATETIME NOT NULL ,
PRIMARY KEY (`ID`)) 
ENGINE = InnoDB DEFAULT CHARSET=UTF8;

GRANT ALL ON users TO ms_users_app;
ALTER USER 'ms_users_app'@'%' IDENTIFIED WITH 'mysql_native_password' BY 'userspw';
FLUSH PRIVILEGES;